# 9.1 Convolution

## Preparation

In [13]:
import torch 
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from scipy import ndimage, misc

## Concept of CNN

In [4]:
conv = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3)

In [3]:
conv.state_dict()['weight'][0][0]=torch.tensor([[1.0,0,-1.0],[2.0,0,-2.0],[1.0,0.0,-1.0]])
conv.state_dict()['bias'][0]=0.0
conv.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  0., -1.],
                        [ 2.,  0., -2.],
                        [ 1.,  0., -1.]]]])),
             ('bias', tensor([0.]))])

In [5]:
image = torch.zeros(1, 1, 5, 5)
image[0, 0, :, 2] = 1
image

tensor([[[[0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 1., 0., 0.]]]])

In [6]:
z = conv(image)
z

tensor([[[[-0.2838,  0.0218, -0.3983],
          [-0.2838,  0.0218, -0.3983],
          [-0.2838,  0.0218, -0.3983]]]], grad_fn=<MkldnnConvolutionBackward>)

## Determining the Size of the Output

In [14]:
# Create a kernal (size = 2)
K = 2
conv1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=K)

In [19]:
conv1.state_dict()['weight'][0][0] = torch.tensor([[1., 1.], [1., 1.]])
conv1.state_dict()['bias'][0] = torch.tensor(0.)
conv1.state_dict()

OrderedDict([('weight',
              tensor([[[[1., 1.],
                        [1., 1.]]]])),
             ('bias', tensor([0.]))])

In [17]:
conv1

Conv2d(1, 1, kernel_size=(2, 2), stride=(1, 1))

In [21]:
# Create an image (size=4)
M=4
image = torch.ones(1, 1, M, M)
image

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [24]:
z1 = conv1(image)
print(z1)
print(z1.shape)

tensor([[[[4., 4., 4.],
          [4., 4., 4.],
          [4., 4., 4.]]]], grad_fn=<MkldnnConvolutionBackward>)
torch.Size([1, 1, 3, 3])


## Stride parameter

In [32]:
# Create a convolution object (stride = 2)
conv2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=2)

In [33]:
# Set the weight and bias
conv2.state_dict()

OrderedDict([('weight',
              tensor([[[[ 0.1083,  0.1299],
                        [-0.1093,  0.4509]]]])),
             ('bias', tensor([0.1440]))])

In [35]:
# Set the weight and bias
conv2.state_dict()['weight'][0][0] = torch.tensor([[ 1., 1.], [-1., -1.]])
conv2.state_dict()['bias'][0] = torch.tensor(0.)
conv2.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  1.],
                        [-1., -1.]]]])),
             ('bias', tensor([0.]))])

In [36]:
z2 = conv2(image)
z2

tensor([[[[0., 0.],
          [0., 0.]]]], grad_fn=<MkldnnConvolutionBackward>)

In [37]:
z2.shape[2:4]

torch.Size([2, 2])

## Zero Padding 

In [41]:
# Create a convolution object (stride = 3)
conv3 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=3)

In [42]:
# Set the weight and bias
conv3.state_dict()

OrderedDict([('weight',
              tensor([[[[-0.1695, -0.2179],
                        [ 0.1537,  0.1280]]]])),
             ('bias', tensor([-0.3709]))])

In [43]:
# Set the weight and bias
conv3.state_dict()['weight'][0][0] = torch.tensor([[ 1., 1.], [-1., -1.]])
conv3.state_dict()['bias'][0] = torch.tensor(0.)
conv3.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  1.],
                        [-1., -1.]]]])),
             ('bias', tensor([0.]))])

In [45]:
z3 = conv3(image)
z3

tensor([[[[0.]]]], grad_fn=<MkldnnConvolutionBackward>)

In [46]:
# Create a convolution object (stride = 3, zero_padding = 1)
conv4 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2, stride=3, padding=1)

In [47]:
# Set the weight and bias
conv4.state_dict()

OrderedDict([('weight',
              tensor([[[[ 0.4329, -0.3271],
                        [ 0.1326,  0.2493]]]])),
             ('bias', tensor([0.3158]))])

In [48]:
# Set the weight and bias
conv4.state_dict()['weight'][0][0] = torch.tensor([[ 1., 1.], [-1., -1.]])
conv4.state_dict()['bias'][0] = torch.tensor(0.)
conv4.state_dict()

OrderedDict([('weight',
              tensor([[[[ 1.,  1.],
                        [-1., -1.]]]])),
             ('bias', tensor([0.]))])

In [50]:
image

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [49]:
z4 = conv4(image)
z4

tensor([[[[-1., -2.],
          [ 0.,  0.]]]], grad_fn=<MkldnnConvolutionBackward>)